### ISSUE TITLE
[1.15.5] .NetFramework change from 4.5.2 to 4.6.1

### ISSUE THREAD

**Issue by JBraunsmaJr** [anegostudios/vsmodtemplate#21]
# Installed Game Version 1.15.5 (stable)

## Steps to reproduce issue

Following the [guide](https://wiki.vintagestory.at/index.php?title=Modding:Setting_up_your_Development_Environment)

1. Download Project Template 1.5.5
2. Execute vsmodtools.exe  --- run the command "setup"
3. Compile project in IDE of choice 

- IDE stated that dependencies were compiled using 4.6.1 so it wouldn't compile the template project

## Solution
Changed target framework from 4.5.2 to 4.6.1 project compiled and started the game as expected

**Comment by tyronx** [comment]
fixed with your MR 👍
