### ISSUE TITLE
Can't setup if VS not in default install path

### ISSUE THREAD

**Issue by PanPraescribens** [anegostudios/vsmodtemplate#24]
Vintage Story is installed in C:\Program Files for me, but modtools.exe is searching in (x86).
It then asks me for a custom path, which I provide.
I get and error because it reads it as C:\Program.
So I then use double quotes as is standard, and I get nothing either!
> Searching for VS in ""C:\Program Files\Vintagestory"..."

Only way this works is if you don't give up just yet and type :
> setup "C:\Program Files\Vintagestory"

**Comment by Th3Dilli** [comment]
I guess that would be some escaping issue as Dark pointed out for this repo but in https://github.com/anegostudios/vsmodtools

although the modtools.exe has been deprecated since we can now cover all it needs with the new template

so I will close this here
