### ISSUE TITLE
Trying to setup dosent work for me

### ISSUE THREAD

**Issue by nkoske** [anegostudios/vsmodtemplate#26]
i dont know what to do here...
GameVersion : 1.18.10(stable)
i did checked the directory and its the Vintage Story directory
[issue.txt](https://github.com/anegostudios/vsmodtemplate/files/12641536/issue.txt)

**Comment by Th3Dilli** [comment]
please check out the readme on this repository or our wiki guide to get started setting up a mod (also on the readme)
https://wiki.vintagestory.at/index.php/Modding:Setting_up_your_Development_Environment

the vs modtools are no longer needed and not up to date for the new template

**Comment by nkoske** [comment]
Thank you, im new into Modding and found a Youtube Tutorial mention this Repository. so i wanted to give it a shot

**Comment by Th3Dilli** [comment]
if you have any questions the best way to ask is on [Discord](https://discord.gg/CkJjdrB) in #mod-development channel
