### ISSUE TITLE
Ambiguous licensing terms

### ISSUE THREAD

**Issue by bluelightning32** [anegostudios/vsmodtemplate#27]
The GPL-2.0 is incorrectly applied to the template. The only reference to licensing in the template is the LICENSE file which contains a copy of the GPL-2.0 license. The directions in that license file say that a license notice should be placed at the top of every file. The [GPL website](https://www.gnu.org/licenses/gpl-howto.en.html) also says that a license notice should be put at the top of every file. That license notice should declare whether the file is licensed under GPL-2.0, any version of GPL, or GPL-2.0 or later. So in the current state, it is unclear what license the template is under.

Do the Vintage Story game developers want all mods to be open source? The official mod database does not push mod developers to use an open source license. Using a GPL license for the official mod template strongly pushes mode developers into making open source mods. However, if the intention is really for developers to make open source mods, the mod template readme should have directions on how to properly comply with the licensing terms. Most likely many developers are unaware that their mods that use different licenses are violating the licensing terms.

I think that a [public domain equivalent license](https://en.wikipedia.org/wiki/Public-domain-equivalent_license) would be more appropriate for a mod template.

**Comment by tyronx** [comment]
adapting the public domain license for the mod template sounds good to me 👍

**Comment by tyronx** [comment]
@Th3Dilli can you change that please
