### ISSUE TITLE
modicon is not included in package

### ISSUE THREAD

**Issue by egocarib** [anegostudios/vsmodtemplate#28]
When present, the modicon file -- such as `modicon.png` -- is not packaged with the rest of the mod.

Can be remedied by modifying CakeBuild/Program.cs to include a line similar to the following, but would be nice to have this automatically included in the template for each newly created mod.

```
context.CopyFile($"../{BuildContext.ProjectName}/modicon.png", $"../Releases/{context.Name}/modicon.png");
```

**Comment by Th3Dilli** [comment]
thank you I have now added that
