### ISSUE TITLE
Update or delete releases

### ISSUE THREAD

**Issue by copygirl** [anegostudios/vsmodtemplate#31]
Another user ran into an issue where they could not compile because they used an old release rather following the instructions correctly. Though I can see how the wording can be mistook when skimming, and downloading the release looks like a valid way to do it. (See: anegostudios/VintageStory-Issues#4538)

Could be fixed by either updating the releases, and keeping them up to date, which seems rather pointless, just adding additional work, or getting rid of the releases entirely. I don't know if anything would be lost by doing this, since presumably you can check out an older version of the repo if you wanted to develop mods for older Vintage Story versions?

**Comment by tyronx** [comment]
thanks, we removed the link to releases now

**Comment by copygirl** [comment]
Ah, I did not realize that releases can be hidden from the main page without removing them. That's a good way to do it, too.
